version: '2'

services:
  # Etcd for our service registry
  etcd:
    image: quay.io/coreos/etcd:v2.3.6
    command: [ -advertise-client-urls, "http://${KILLRVIDEO_DOCKER_IP}:2379", -listen-client-urls, "http://0.0.0.0:2379" ]
    ports:
    # The client port
    - "2379:2379"
    environment:
      SERVICE_2379_NAME: etcd

  # Registrator to register containers with Etcd
  registrator:
    image: gliderlabs/registrator:latest
    # Tell registrator where the etcd HTTP API is and to use the docker VM's IP
    command: [ -ip, "$KILLRVIDEO_DOCKER_IP", "etcd://etcd:2379/killrvideo/services" ]
    volumes:
    # So registrator can use the docker API to inspect containers
    - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
    - etcd
    
  # cassandra
  cassandra:
    image: cassandra:3.7
    ports:
    - "9042:9042"
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
    environment:
      SERVICE_9042_NAME: cassandra
  
  #Web front end
  web:
    image: killrvideo/killrvideo-web:1.2.0
    ports:
    - "3000:3000"
    depends_on:
    - cassandra
    - etcd
    environment:
      SERVICE_3000_NAME: web
      KILLRVIDEO_ETCD: "etcd:2379"
